/**
 * Author: Ngum buka Fon Nyuydze
 * email: ngumbukafon@gmail.com
 */
@isTest
public class LeadInterviewControllerTest {
    @TestSetup
    static void createLeadInterviews(){
        
    }

    @isTest 
    static void deleteLeadInterviewTest(){
        //insert lead interviews and attempt delete
        
    }

    @isTest 
    static void getLeadInterviewsTest(){
        // insert records and try to get them
    }
}

